language: node_js
node_js:
  - '11.7.0'
install:
  - yarn
script: yarn lint && yarn test
before_deploy: yarn build
deploy:
  provider: npm
  email: 1253478653@qq.com
  skip_cleanup: true
  api_key:
    secure: 'e54055d6-5d1d-45f6-b9eb-01fc6796e4e3'
  on:
    tags: true
    branch: master
  tag: latest
